language: android

android:
  components:
    - tools
    # YooxApp, YooxLibrary and YooxAndroidSDK
    - build-tools-23.0.2
    # YooxApp, YooxLibrary and YooxAndroidSDK
    - android-23
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script:
    - ./gradlew test
    - ./gradlew assembleDebug

after_success:
    - bash <(curl -s https://codecov.io/bash)
